### ISSUE TITLE
Change About Page Text

### ISSUE THREAD

**Issue by neophyte-programmer** [208-code-titans/bettina-snacks#72]
Change text from Lorem ipsum to actual stuff

**Comment by suraj1609** [comment]
Hey, I am Suraj Kanse . How can I contribute to this open source project for my open source class? Please assign me a task.
Contact Me: [kansesuda19ie@student.mes.ac.in](mailto:kansesuda19ie@student.mes.ac.in)
GitHub: @suraj1609
